name: 'Continuous Integration'
on: [ push, workflow_dispatch ]
jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: hub.xenit.eu
          username: ${{ secrets.XENIT_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.XENIT_DOCKER_REGISTRY_PASSWORD }}
      - name: Unit tests
        uses: gradle/gradle-build-action@v2.3.0
        with:
          cache-read-only: false
          arguments: test --info
      - name: Integration tests
        uses: gradle/gradle-build-action@v2.3.0
        with:
          cache-read-only: false
          arguments: integrationTest --info -Pservice.alfresco.tcp.8080=8080 -Pservice.alfresco.tcp.8443=8443
      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: /home/runner/work/**/build/**/reports/
          retention-days: 2
      - name: Publish to Maven Central / Sonatype
        if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
        uses: gradle/gradle-build-action@v2.3.0
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        with:
          arguments: publish --info -PsigningKeyId=DF8285F0